<a href="https://colab.research.google.com/github/nidhigadekar2764-png/Pandas-Data-Analysis/blob/main/pandas_xsls.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df.head()

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
0,O1001,C101,2026-01-03,Electronics,Laptop,North,1,58999.0,Completed,Credit Card,0.05,Ananya,High,5.0
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499.0,Completed,UPI,0.10,Rohan,Medium,4.0
2,O1003,C103,2026-01-07,electronics,Wireless Mouse,North,2,2498.0,Pending,UPI,0.00,Rohan,Low,NaN
3,O1004,C104,2026-01-09,Office,Ergonomic Chair,South,1,18499.0,Completed,Debit Card,0.15,Ananya,High,5.0
4,O1005,C105,2026-01-11,Home,Air Fryer,West,1,7999.0,Cancelled,Credit Card,0.00,Meera,Medium,NaN

In [ ]:
file = '/content/Pandas_Practice_Dataset.xlsx'

In [ ]:
excel = pd.ExcelFile(file)

In [ ]:
excel.sheet_names

['Orders_Raw', 'Customers', 'Orders_Jan', 'Orders_Feb', 'Customers_Alt_Key']

In [ ]:
Orders_Raw = pd.read_excel(file,sheet_name = 'Orders_Raw')

In [ ]:
Orders_Raw.head()

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
0,O1001,C101,2026-01-03,Electronics,Laptop,North,1,58999.0,Completed,Credit Card,0.05,Ananya,High,5.0
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499.0,Completed,UPI,0.10,Rohan,Medium,4.0
2,O1003,C103,2026-01-07,electronics,Wireless Mouse,North,2,2498.0,Pending,UPI,0.00,Rohan,Low,NaN
3,O1004,C104,2026-01-09,Office,Ergonomic Chair,South,1,18499.0,Completed,Debit Card,0.15,Ananya,High,5.0
4,O1005,C105,2026-01-11,Home,Air Fryer,West,1,7999.0,Cancelled,Credit Card,0.00,Meera,Medium,NaN

In [ ]:
Customer = pd.read_excel(file,sheet_name = 'Customers')

In [ ]:
Customer.head()

  customer_id customer_name       city    segment signup_date loyalty_tier
0        C101    Aisha Khan     Mumbai     Retail  2025-03-12         Gold
1        C102   Rahul Verma       Pune  Corporate  2025-04-08       Silver
2        C103     Neha Iyer  Bengaluru     Retail  2025-05-19       Silver
3        C104   Arjun Mehta      Delhi  Corporate  2025-01-24         Gold
4        C105   Sara Joseph      Kochi     Retail  2025-06-02       Bronze

In [ ]:
Orders_Raw = pd.read_excel(file,sheet_name = 'Orders_Raw')

In [ ]:
Orders_Raw.head()

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
0,O1001,C101,2026-01-03,Electronics,Laptop,North,1,58999.0,Completed,Credit Card,0.05,Ananya,High,5.0
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499.0,Completed,UPI,0.10,Rohan,Medium,4.0
2,O1003,C103,2026-01-07,electronics,Wireless Mouse,North,2,2498.0,Pending,UPI,0.00,Rohan,Low,NaN
3,O1004,C104,2026-01-09,Office,Ergonomic Chair,South,1,18499.0,Completed,Debit Card,0.15,Ananya,High,5.0
4,O1005,C105,2026-01-11,Home,Air Fryer,West,1,7999.0,Cancelled,Credit Card,0.00,Meera,Medium,NaN

In [ ]:
Orders_Raw.shape

(20, 14)

In [ ]:
Orders_Raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        20 non-null     object
 1   customer_id     20 non-null     object
 2   order_date      20 non-null     object
 3   category        20 non-null     object
 4   product         20 non-null     object
 5   region          18 non-null     object
 6   quantity        20 non-null     int64
 7   amount          18 non-null     float64
 8   status          20 non-null     object
 9   payment_method  20 non-null     object
 10  discount_pct    20 non-null     float64
 11  sales_rep       20 non-null     object
 12  priority        20 non-null     object
 13  rating          18 non-null     float64
dtypes: float64(3), int64(1), object(10)
memory usage: 2.3+ KB

In [ ]:
Orders_Raw.isna().sum()

order_id          0
customer_id       0
order_date        0
category          0
product           0
region            2
quantity          0
amount            2
status            0
payment_method    0
discount_pct      0
sales_rep         0
priority          0
rating            2
dtype: int64

In [ ]:
Orders_Raw[Orders_Raw['amount']>5000]

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
0,O1001,C101,2026-01-03,Electronics,Laptop,North,1,58999.0,Completed,Credit Card,0.05,Ananya,High,5.0
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499.0,Completed,UPI,0.10,Rohan,Medium,4.0
3,O1004,C104,2026-01-09,Office,Ergonomic Chair,South,1,18499.0,Completed,Debit Card,0.15,Ananya,High,5.0
4,O1005,C105,2026-01-11,Home,Air Fryer,West,1,7999.0,Cancelled,Credit Card,0.00,Meera,Medium,NaN
5,O1006,C106,2026-01-14,Electronics,Monitor,East,2,39998.0,Completed,Credit Card,0.08,Ananya,High,4.0
7,O1008,C107,2026-01-21,Furniture,Bookshelf,West,1,9999.0,Returned,COD,0.00,Rohan,Medium,2.0
8,O1009,C108,2026-01-25,Office,Printer,NaN,1,15999.0,Completed,Credit Card,0.05,Meera,Medium,3.0
9,O1010,C109,2026-01-29,Electronics,Keyboard,north,2,5998.0,completed,UPI,0.00,Ananya,Low,4.0
10,O1011,C102,2026-02-02,Home,Mixer Grinder,East,1,6499.0,Completed,UPI,0.10,Rohan,Medium,5.0
11,O1012,C103,2026-02-05,Sports,Dumbbells,North,2,6998.0,Completed,Debit Card,0.05,Meera,Medium,4.0
12,O1013,C104,2026-02-08,Furniture,Office Table,South,1,21999.0,Pending,Credit Card,0.12,Ananya,High,4.0
15,O1016,C999,2026-02-17,Home,Vacuum Cleaner,South,1,13999.0,Completed,COD,0.10,Ananya,Medium,4.0
16,O1017,C107,2026-02-20,Electronics,Tablet,West,1,28999.0,Returned,Credit Card,0.07,Meera,High,2.0
17,O1018,C108,2026-02-23,Furniture,Side Table,NaN,2,8998.0,Completed,UPI,0.05,Rohan,Medium,4.0

In [ ]:
Order_Jan=pd.read_excel(file,sheet_name = 'Orders_Jan')

In [ ]:
Order_Jan.head()

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
0,O1001,C101,2026-01-03,Electronics,Laptop,North,1,58999,Completed,Credit Card,0.05,Ananya,High,5.0
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499,Completed,UPI,0.10,Rohan,Medium,4.0
2,O1003,C103,2026-01-07,electronics,Wireless Mouse,North,2,2498,Pending,UPI,0.00,Rohan,Low,NaN
3,O1004,C104,2026-01-09,Office,Ergonomic Chair,South,1,18499,Completed,Debit Card,0.15,Ananya,High,5.0
4,O1005,C105,2026-01-11,Home,Air Fryer,West,1,7999,Cancelled,Credit Card,0.00,Meera,Medium,NaN

In [ ]:
print(order_raw['product'])
Orders_Feb = pd.read_excel(file, sheet_name="Orders_Feb")

0              Laptop
1                Desk
2      Wireless Mouse
3     Ergonomic Chair
4           Air Fryer
5             Monitor
6            Yoga Mat
7           Bookshelf
8             Printer
9            Keyboard
10      Mixer Grinder
11          Dumbbells
12       Office Table
13             Webcam
14      Notebook Pack
15     Vacuum Cleaner
16             Tablet
17         Side Table
18     Paper Shredder
19     Paper Shredder
Name: product, dtype: object

In [ ]:
Orders_Feb.head()

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
0,O1011,C102,2026-02-02,Home,Mixer Grinder,East,1,6499.0,Completed,UPI,0.10,Rohan,Medium,5
1,O1012,C103,2026-02-05,Sports,Dumbbells,North,2,6998.0,Completed,Debit Card,0.05,Meera,Medium,4
2,O1013,C104,2026-02-08,Furniture,Office Table,South,1,21999.0,Pending,Credit Card,0.12,Ananya,High,4
3,O1014,C105,2026-02-11,Electronics,Webcam,West,1,3999.0,Completed,Credit Card,0.00,Meera,Low,3
4,O1015,C106,2026-02-14,Office,Notebook Pack,East,5,2495.0,Completed,UPI,0.05,Rohan,Low,5

In [ ]:
# select product, catagory. amount from tablename;

In [ ]:
order_raw[
    (order_raw['category'] == 'Furniture') &
    (order_raw['amount'] > 10000)
]

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499.0,Completed,UPI,0.10,Rohan,Medium,4.0
12,O1013,C104,2026-02-08,Furniture,Office Table,South,1,21999.0,Pending,Credit Card,0.12,Ananya,High,4.0

In [ ]:
print(order_raw['product'])

0              Laptop
1                Desk
2      Wireless Mouse
3     Ergonomic Chair
4           Air Fryer
5             Monitor
6            Yoga Mat
7           Bookshelf
8             Printer
9            Keyboard
10      Mixer Grinder
11          Dumbbells
12       Office Table
13             Webcam
14      Notebook Pack
15     Vacuum Cleaner
16             Tablet
17         Side Table
18     Paper Shredder
19     Paper Shredder
Name: product, dtype: object

In [ ]:
#select catagory from tablename
# where catagory = funiture;

#find orders belonging to funiture catagory

In [ ]:
import pandas as pd

In [ ]:
order_raw = pd.read_excel('/content/Pandas_Practice_Dataset.xlsx',sheet_name = 'Orders_Raw')

In [ ]:
order_raw[order_raw['category'] == 'Furniture']

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499.0,Completed,UPI,0.10,Rohan,Medium,4.0
7,O1008,C107,2026-01-21,Furniture,Bookshelf,West,1,9999.0,Returned,COD,0.00,Rohan,Medium,2.0
12,O1013,C104,2026-02-08,Furniture,Office Table,South,1,21999.0,Pending,Credit Card,0.12,Ananya,High,4.0
17,O1018,C108,2026-02-23,Furniture,Side Table,NaN,2,8998.0,Completed,UPI,0.05,Rohan,Medium,4.0

In [ ]:
order_raw[['product', 'category', 'amount']]

            product     category   amount
0            Laptop  Electronics  58999.0
1              Desk    Furniture  12499.0
2    Wireless Mouse  electronics   2498.0
3   Ergonomic Chair       Office  18499.0
4         Air Fryer         Home   7999.0
5           Monitor  Electronics  39998.0
6          Yoga Mat       Sports   4497.0
7         Bookshelf    Furniture   9999.0
8           Printer       Office  15999.0
9          Keyboard  Electronics   5998.0
10    Mixer Grinder         Home   6499.0
11        Dumbbells       Sports   6998.0
12     Office Table    Furniture  21999.0
13           Webcam  Electronics   3999.0
14    Notebook Pack       Office   2495.0
15   Vacuum Cleaner         Home  13999.0
16           Tablet  Electronics  28999.0
17       Side Table    Furniture   8998.0
18   Paper Shredder       Office      NaN
19   Paper Shredder       Office      NaN

In [ ]:
order_raw[order_raw['amount'] > 10000]

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
0,O1001,C101,2026-01-03,Electronics,Laptop,North,1,58999.0,Completed,Credit Card,0.05,Ananya,High,5.0
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499.0,Completed,UPI,0.10,Rohan,Medium,4.0
3,O1004,C104,2026-01-09,Office,Ergonomic Chair,South,1,18499.0,Completed,Debit Card,0.15,Ananya,High,5.0
5,O1006,C106,2026-01-14,Electronics,Monitor,East,2,39998.0,Completed,Credit Card,0.08,Ananya,High,4.0
8,O1009,C108,2026-01-25,Office,Printer,NaN,1,15999.0,Completed,Credit Card,0.05,Meera,Medium,3.0
12,O1013,C104,2026-02-08,Furniture,Office Table,South,1,21999.0,Pending,Credit Card,0.12,Ananya,High,4.0
15,O1016,C999,2026-02-17,Home,Vacuum Cleaner,South,1,13999.0,Completed,COD,0.10,Ananya,Medium,4.0
16,O1017,C107,2026-02-20,Electronics,Tablet,West,1,28999.0,Returned,Credit Card,0.07,Meera,High,2.0

In [ ]:
order_raw[order_raw['status'] == 'Completed']

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
0,O1001,C101,2026-01-03,Electronics,Laptop,North,1,58999.0,Completed,Credit Card,0.05,Ananya,High,5.0
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499.0,Completed,UPI,0.10,Rohan,Medium,4.0
3,O1004,C104,2026-01-09,Office,Ergonomic Chair,South,1,18499.0,Completed,Debit Card,0.15,Ananya,High,5.0
5,O1006,C106,2026-01-14,Electronics,Monitor,East,2,39998.0,Completed,Credit Card,0.08,Ananya,High,4.0
6,O1007,C101,2026-01-18,Sports,Yoga Mat,North,3,4497.0,Completed,UPI,0.05,Meera,Low,4.0
8,O1009,C108,2026-01-25,Office,Printer,NaN,1,15999.0,Completed,Credit Card,0.05,Meera,Medium,3.0
10,O1011,C102,2026-02-02,Home,Mixer Grinder,East,1,6499.0,Completed,UPI,0.10,Rohan,Medium,5.0
11,O1012,C103,2026-02-05,Sports,Dumbbells,North,2,6998.0,Completed,Debit Card,0.05,Meera,Medium,4.0
13,O1014,C105,2026-02-11,Electronics,Webcam,West,1,3999.0,Completed,Credit Card,0.00,Meera,Low,3.0
14,O1015,C106,2026-02-14,Office,Notebook Pack,East,5,2495.0,Completed,UPI,0.05,Rohan,Low,5.0
15,O1016,C999,2026-02-17,Home,Vacuum Cleaner,South,1,13999.0,Completed,COD,0.10,Ananya,Medium,4.0
17,O1018,C108,2026-02-23,Furniture,Side Table,NaN,2,8998.0,Completed,UPI,0.05,Rohan,Medium,4.0

In [ ]:
order_raw[
    (order_raw['category'] == 'Furniture') &
    (order_raw['amount'] > 10000)
]

,order_id,customer_id,order_date,category,product,region,quantity,amount,status,payment_method,discount_pct,sales_rep,priority,rating
1,O1002,C102,2026-01-05,Furniture,Desk,East,1,12499.0,Completed,UPI,0.10,Rohan,Medium,4.0
12,O1013,C104,2026-02-08,Furniture,Office Table,South,1,21999.0,Pending,Credit Card,0.12,Ananya,High,4.0

In [ ]:
order_raw.groupby('category')['amount'].sum()

category
Electronics    137993.0
Furniture       53495.0
Home            28497.0
Office          36993.0
Sports          11495.0
electronics      2498.0
Name: amount, dtype: float64

In [ ]:
# Total amount spent per category
category_summary = order_raw.groupby('category')['amount'].sum()
print(category_summary)

category
Electronics    137993.0
Furniture       53495.0
Home            28497.0
Office          36993.0
Sports          11495.0
electronics      2498.0
Name: amount, dtype: float64

In [ ]:
# Remove duplicate rows from order_raw
orders = order_raw.drop_duplicates()

In [ ]:
# Check which columns have NaN values
print(order_raw.isna().sum())

order_id          0
customer_id       0
order_date        0
category          0
product           0
region            2
quantity          0
amount            2
status            0
payment_method    0
discount_pct      0
sales_rep         0
priority          0
rating            2
dtype: int64

In [ ]:
# Option A: Fill missing numerical ratings with the average rating
order_raw['rating'] = order_raw['rating'].fillna(order_raw['rating'].mean())

In [ ]:
# Option B: Fill missing priority with 'Not Specified'
order_raw['priority'] = order_raw['priority'].fillna('Not Specified')

In [ ]:

# Merge orders with customer profile data
merged_df = pd.merge(order_raw, Customer, on='customer_id', how='left')